// Copyright (c) FIRST and other WPILib contributors.
// Open Source Software; you can modify and/or share it under the terms of
// the WPILib BSD license file in the root directory of this project.

// THIS FILE WAS AUTO-GENERATED BY ./wpiunits/generate_units.py. DO NOT MODIFY

package digilib.units.voltsperangacc;

import edu.wpi.first.units.*;
import edu.wpi.first.units.measure.*;

import static digilib.units.voltsperangacc.VoltsPerAngularAccelerationUnit.VoltsPerRadiansPerSecondPerSecond;

@SuppressWarnings({"unchecked", "cast", "checkstyle", "PMD"})
public interface VoltsPerAngularAcceleration extends Measure<VoltsPerAngularAccelerationUnit> {
    static VoltsPerAngularAcceleration ofRelativeUnits(double magnitude, VoltsPerAngularAccelerationUnit unit) {
        return new ImmutableVoltsPerAngularAcceleration(magnitude, unit.toBaseUnits(magnitude), unit);
    }

    static VoltsPerAngularAcceleration ofBaseUnits(double baseUnitMagnitude, VoltsPerAngularAccelerationUnit unit) {
        return new ImmutableVoltsPerAngularAcceleration(unit.fromBaseUnits(baseUnitMagnitude), baseUnitMagnitude, unit);
    }

    @Override
    VoltsPerAngularAcceleration copy();

    @Override
    default MutVoltsPerAngularAcceleration mutableCopy() {
        return new MutVoltsPerAngularAcceleration(magnitude(), baseUnitMagnitude(), unit());
    }

    @Override
    VoltsPerAngularAccelerationUnit unit();

    @Override
    default VoltsPerAngularAccelerationUnit baseUnit() { return unit().getBaseUnit(); }

    @Override
    default double in(VoltsPerAngularAccelerationUnit unit) {
        return unit.fromBaseUnits(baseUnitMagnitude());
    }

    @Override
    default VoltsPerAngularAcceleration unaryMinus() {
        return unit().ofBaseUnits(0 - baseUnitMagnitude());
    }

    @Override
    default VoltsPerAngularAcceleration plus(Measure<? extends VoltsPerAngularAccelerationUnit> other) {
        return unit().ofBaseUnits(baseUnitMagnitude() + other.baseUnitMagnitude());
    }

    @Override
    default VoltsPerAngularAcceleration minus(Measure<? extends VoltsPerAngularAccelerationUnit> other) {
        return unit().ofBaseUnits(baseUnitMagnitude() - other.baseUnitMagnitude());
    }

    @Override
    default VoltsPerAngularAcceleration times(double multiplier) {
        return unit().ofBaseUnits(baseUnitMagnitude() * multiplier);
    }

    @Override
    default VoltsPerAngularAcceleration div(double divisor) {
        return unit().ofBaseUnits(baseUnitMagnitude() / divisor);
    }

    @Override
    default Mult<VoltsPerAngularAccelerationUnit, AccelerationUnit<?>> times(Acceleration<?> multiplier) {
        return (Mult<VoltsPerAngularAccelerationUnit, AccelerationUnit<?>>) Measure.super.times(multiplier);
    }

    @Override
    default Per<VoltsPerAngularAccelerationUnit, AccelerationUnit<?>> div(Acceleration<?> divisor) {
        return (Per<VoltsPerAngularAccelerationUnit, AccelerationUnit<?>>) Measure.super.div(divisor);
    }

    @Override
    default Per<VoltsPerAngularAccelerationUnit, AccelerationUnit<?>> per(AccelerationUnit<?> divisorUnit) {
        return div(divisorUnit.one());
    }

    @Override
    default Mult<VoltsPerAngularAccelerationUnit, AngleUnit> times(Angle multiplier) {
        return (Mult<VoltsPerAngularAccelerationUnit, AngleUnit>) Measure.super.times(multiplier);
    }

    @Override
    default Per<VoltsPerAngularAccelerationUnit, AngleUnit> div(Angle divisor) {
        return (Per<VoltsPerAngularAccelerationUnit, AngleUnit>) Measure.super.div(divisor);
    }

    @Override
    default Per<VoltsPerAngularAccelerationUnit, AngleUnit> per(AngleUnit divisorUnit) {
        return div(divisorUnit.one());
    }


    @Override
    default Voltage times(AngularAcceleration multiplier) {
        return (Voltage) Measure.super.times(multiplier);
    }

    @Override
    default Per<VoltsPerAngularAccelerationUnit, AngularAccelerationUnit> div(AngularAcceleration divisor) {
        return (Per<VoltsPerAngularAccelerationUnit, AngularAccelerationUnit>) Measure.super.div(divisor);
    }

    @Override
    default Per<VoltsPerAngularAccelerationUnit, AngularAccelerationUnit> per(AngularAccelerationUnit divisorUnit) {
        return div(divisorUnit.one());
    }


    @Override
    default Mult<VoltsPerAngularAccelerationUnit, AngularMomentumUnit> times(AngularMomentum multiplier) {
        return (Mult<VoltsPerAngularAccelerationUnit, AngularMomentumUnit>) Measure.super.times(multiplier);
    }

    @Override
    default Per<VoltsPerAngularAccelerationUnit, AngularMomentumUnit> div(AngularMomentum divisor) {
        return (Per<VoltsPerAngularAccelerationUnit, AngularMomentumUnit>) Measure.super.div(divisor);
    }

    @Override
    default Per<VoltsPerAngularAccelerationUnit, AngularMomentumUnit> per(AngularMomentumUnit divisorUnit) {
        return div(divisorUnit.one());
    }


    @Override
    default Mult<VoltsPerAngularAccelerationUnit, AngularVelocityUnit> times(AngularVelocity multiplier) {
        return (Mult<VoltsPerAngularAccelerationUnit, AngularVelocityUnit>) Measure.super.times(multiplier);
    }

    @Override
    default Per<VoltsPerAngularAccelerationUnit, AngularVelocityUnit> div(AngularVelocity divisor) {
        return (Per<VoltsPerAngularAccelerationUnit, AngularVelocityUnit>) Measure.super.div(divisor);
    }

    @Override
    default Per<VoltsPerAngularAccelerationUnit, AngularVelocityUnit> per(AngularVelocityUnit divisorUnit) {
        return div(divisorUnit.one());
    }


    @Override
    default Mult<VoltsPerAngularAccelerationUnit, CurrentUnit> times(Current multiplier) {
        return (Mult<VoltsPerAngularAccelerationUnit, CurrentUnit>) Measure.super.times(multiplier);
    }

    @Override
    default Per<VoltsPerAngularAccelerationUnit, CurrentUnit> div(Current divisor) {
        return (Per<VoltsPerAngularAccelerationUnit, CurrentUnit>) Measure.super.div(divisor);
    }

    @Override
    default Per<VoltsPerAngularAccelerationUnit, CurrentUnit> per(CurrentUnit divisorUnit) {
        return div(divisorUnit.one());
    }

    @Override
    default VoltsPerAngularAcceleration div(Dimensionless divisor) {
        return VoltsPerRadiansPerSecondPerSecond.of(baseUnitMagnitude() / divisor.baseUnitMagnitude());
    }

    @Override
    default VoltsPerAngularAcceleration times(Dimensionless multiplier) {
        return VoltsPerRadiansPerSecondPerSecond.of(baseUnitMagnitude() * multiplier.baseUnitMagnitude());
    }


    @Override
    default Mult<VoltsPerAngularAccelerationUnit, DistanceUnit> times(Distance multiplier) {
        return (Mult<VoltsPerAngularAccelerationUnit, DistanceUnit>) Measure.super.times(multiplier);
    }

    @Override
    default Per<VoltsPerAngularAccelerationUnit, DistanceUnit> div(Distance divisor) {
        return (Per<VoltsPerAngularAccelerationUnit, DistanceUnit>) Measure.super.div(divisor);
    }

    @Override
    default Per<VoltsPerAngularAccelerationUnit, DistanceUnit> per(DistanceUnit divisorUnit) {
        return div(divisorUnit.one());
    }


    @Override
    default Mult<VoltsPerAngularAccelerationUnit, EnergyUnit> times(Energy multiplier) {
        return (Mult<VoltsPerAngularAccelerationUnit, EnergyUnit>) Measure.super.times(multiplier);
    }

    @Override
    default Per<VoltsPerAngularAccelerationUnit, EnergyUnit> div(Energy divisor) {
        return (Per<VoltsPerAngularAccelerationUnit, EnergyUnit>) Measure.super.div(divisor);
    }

    @Override
    default Per<VoltsPerAngularAccelerationUnit, EnergyUnit> per(EnergyUnit divisorUnit) {
        return div(divisorUnit.one());
    }


    @Override
    default Mult<VoltsPerAngularAccelerationUnit, ForceUnit> times(Force multiplier) {
        return (Mult<VoltsPerAngularAccelerationUnit, ForceUnit>) Measure.super.times(multiplier);
    }

    @Override
    default Per<VoltsPerAngularAccelerationUnit, ForceUnit> div(Force divisor) {
        return (Per<VoltsPerAngularAccelerationUnit, ForceUnit>) Measure.super.div(divisor);
    }

    @Override
    default Per<VoltsPerAngularAccelerationUnit, ForceUnit> per(ForceUnit divisorUnit) {
        return div(divisorUnit.one());
    }


    @Override
    default Mult<VoltsPerAngularAccelerationUnit, FrequencyUnit> times(Frequency multiplier) {
        return (Mult<VoltsPerAngularAccelerationUnit, FrequencyUnit>) Measure.super.times(multiplier);
    }

    @Override
    default Per<VoltsPerAngularAccelerationUnit, FrequencyUnit> div(Frequency divisor) {
        return (Per<VoltsPerAngularAccelerationUnit, FrequencyUnit>) Measure.super.div(divisor);
    }

    @Override
    default Per<VoltsPerAngularAccelerationUnit, FrequencyUnit> per(FrequencyUnit divisorUnit) {
        return div(divisorUnit.one());
    }


    @Override
    default Mult<VoltsPerAngularAccelerationUnit, LinearAccelerationUnit> times(LinearAcceleration multiplier) {
        return (Mult<VoltsPerAngularAccelerationUnit, LinearAccelerationUnit>) Measure.super.times(multiplier);
    }

    @Override
    default Per<VoltsPerAngularAccelerationUnit, LinearAccelerationUnit> div(LinearAcceleration divisor) {
        return (Per<VoltsPerAngularAccelerationUnit, LinearAccelerationUnit>) Measure.super.div(divisor);
    }

    @Override
    default Per<VoltsPerAngularAccelerationUnit, LinearAccelerationUnit> per(LinearAccelerationUnit divisorUnit) {
        return div(divisorUnit.one());
    }


    @Override
    default Mult<VoltsPerAngularAccelerationUnit, LinearMomentumUnit> times(LinearMomentum multiplier) {
        return (Mult<VoltsPerAngularAccelerationUnit, LinearMomentumUnit>) Measure.super.times(multiplier);
    }

    @Override
    default Per<VoltsPerAngularAccelerationUnit, LinearMomentumUnit> div(LinearMomentum divisor) {
        return (Per<VoltsPerAngularAccelerationUnit, LinearMomentumUnit>) Measure.super.div(divisor);
    }

    @Override
    default Per<VoltsPerAngularAccelerationUnit, LinearMomentumUnit> per(LinearMomentumUnit divisorUnit) {
        return div(divisorUnit.one());
    }


    @Override
    default Mult<VoltsPerAngularAccelerationUnit, LinearVelocityUnit> times(LinearVelocity multiplier) {
        return (Mult<VoltsPerAngularAccelerationUnit, LinearVelocityUnit>) Measure.super.times(multiplier);
    }

    @Override
    default Per<VoltsPerAngularAccelerationUnit, LinearVelocityUnit> div(LinearVelocity divisor) {
        return (Per<VoltsPerAngularAccelerationUnit, LinearVelocityUnit>) Measure.super.div(divisor);
    }

    @Override
    default Per<VoltsPerAngularAccelerationUnit, LinearVelocityUnit> per(LinearVelocityUnit divisorUnit) {
        return div(divisorUnit.one());
    }


    @Override
    default Mult<VoltsPerAngularAccelerationUnit, MassUnit> times(Mass multiplier) {
        return (Mult<VoltsPerAngularAccelerationUnit, MassUnit>) Measure.super.times(multiplier);
    }

    @Override
    default Per<VoltsPerAngularAccelerationUnit, MassUnit> div(Mass divisor) {
        return (Per<VoltsPerAngularAccelerationUnit, MassUnit>) Measure.super.div(divisor);
    }

    @Override
    default Per<VoltsPerAngularAccelerationUnit, MassUnit> per(MassUnit divisorUnit) {
        return div(divisorUnit.one());
    }


    @Override
    default Mult<VoltsPerAngularAccelerationUnit, MomentOfInertiaUnit> times(MomentOfInertia multiplier) {
        return (Mult<VoltsPerAngularAccelerationUnit, MomentOfInertiaUnit>) Measure.super.times(multiplier);
    }

    @Override
    default Per<VoltsPerAngularAccelerationUnit, MomentOfInertiaUnit> div(MomentOfInertia divisor) {
        return (Per<VoltsPerAngularAccelerationUnit, MomentOfInertiaUnit>) Measure.super.div(divisor);
    }

    @Override
    default Per<VoltsPerAngularAccelerationUnit, MomentOfInertiaUnit> per(MomentOfInertiaUnit divisorUnit) {
        return div(divisorUnit.one());
    }


    @Override
    default Mult<VoltsPerAngularAccelerationUnit, MultUnit<?, ?>> times(Mult<?, ?> multiplier) {
        return (Mult<VoltsPerAngularAccelerationUnit, MultUnit<?, ?>>) Measure.super.times(multiplier);
    }

    @Override
    default Per<VoltsPerAngularAccelerationUnit, MultUnit<?, ?>> div(Mult<?, ?> divisor) {
        return (Per<VoltsPerAngularAccelerationUnit, MultUnit<?, ?>>) Measure.super.div(divisor);
    }

    @Override
    default Per<VoltsPerAngularAccelerationUnit, MultUnit<?, ?>> per(MultUnit<?, ?> divisorUnit) {
        return div(divisorUnit.ofNative(1));
    }


    @Override
    default Mult<VoltsPerAngularAccelerationUnit, PerUnit<?, ?>> times(Per<?, ?> multiplier) {
        return (Mult<VoltsPerAngularAccelerationUnit, PerUnit<?, ?>>) Measure.super.times(multiplier);
    }

    @Override
    default Per<VoltsPerAngularAccelerationUnit, PerUnit<?, ?>> div(Per<?, ?> divisor) {
        return (Per<VoltsPerAngularAccelerationUnit, PerUnit<?, ?>>) Measure.super.div(divisor);
    }

    @Override
    default Per<VoltsPerAngularAccelerationUnit, PerUnit<?, ?>> per(PerUnit<?, ?> divisorUnit) {
        return div(divisorUnit.ofNative(1));
    }


    @Override
    default Mult<VoltsPerAngularAccelerationUnit, PowerUnit> times(Power multiplier) {
        return (Mult<VoltsPerAngularAccelerationUnit, PowerUnit>) Measure.super.times(multiplier);
    }

    @Override
    default Per<VoltsPerAngularAccelerationUnit, PowerUnit> div(Power divisor) {
        return (Per<VoltsPerAngularAccelerationUnit, PowerUnit>) Measure.super.div(divisor);
    }

    @Override
    default Per<VoltsPerAngularAccelerationUnit, PowerUnit> per(PowerUnit divisorUnit) {
        return div(divisorUnit.one());
    }


    @Override
    default Mult<VoltsPerAngularAccelerationUnit, ResistanceUnit> times(Resistance multiplier) {
        return (Mult<VoltsPerAngularAccelerationUnit, ResistanceUnit>) Measure.super.times(multiplier);
    }

    @Override
    default Per<VoltsPerAngularAccelerationUnit, ResistanceUnit> div(Resistance divisor) {
        return (Per<VoltsPerAngularAccelerationUnit, ResistanceUnit>) Measure.super.div(divisor);
    }

    @Override
    default Per<VoltsPerAngularAccelerationUnit, ResistanceUnit> per(ResistanceUnit divisorUnit) {
        return div(divisorUnit.one());
    }


    @Override
    default Mult<VoltsPerAngularAccelerationUnit, TemperatureUnit> times(Temperature multiplier) {
        return (Mult<VoltsPerAngularAccelerationUnit, TemperatureUnit>) Measure.super.times(multiplier);
    }

    @Override
    default Per<VoltsPerAngularAccelerationUnit, TemperatureUnit> div(Temperature divisor) {
        return (Per<VoltsPerAngularAccelerationUnit, TemperatureUnit>) Measure.super.div(divisor);
    }

    @Override
    default Per<VoltsPerAngularAccelerationUnit, TemperatureUnit> per(TemperatureUnit divisorUnit) {
        return div(divisorUnit.one());
    }


    @Override
    default Mult<VoltsPerAngularAccelerationUnit, TimeUnit> times(Time multiplier) {
        return (Mult<VoltsPerAngularAccelerationUnit, TimeUnit>) Measure.super.times(multiplier);
    }

    @Override
    default Velocity<VoltsPerAngularAccelerationUnit> div(Time divisor) {
        return VelocityUnit.combine(unit(), divisor.unit()).ofBaseUnits(baseUnitMagnitude() / divisor.baseUnitMagnitude());
    }

    @Override
    default Velocity<VoltsPerAngularAccelerationUnit> per(TimeUnit divisorUnit) {
        return div(divisorUnit.one());
    }


    @Override
    default Mult<VoltsPerAngularAccelerationUnit, TorqueUnit> times(Torque multiplier) {
        return (Mult<VoltsPerAngularAccelerationUnit, TorqueUnit>) Measure.super.times(multiplier);
    }

    @Override
    default Per<VoltsPerAngularAccelerationUnit, TorqueUnit> div(Torque divisor) {
        return (Per<VoltsPerAngularAccelerationUnit, TorqueUnit>) Measure.super.div(divisor);
    }

    @Override
    default Per<VoltsPerAngularAccelerationUnit, TorqueUnit> per(TorqueUnit divisorUnit) {
        return div(divisorUnit.one());
    }


    @Override
    default Mult<VoltsPerAngularAccelerationUnit, VelocityUnit<?>> times(Velocity<?> multiplier) {
        return (Mult<VoltsPerAngularAccelerationUnit, VelocityUnit<?>>) Measure.super.times(multiplier);
    }

    @Override
    default Per<VoltsPerAngularAccelerationUnit, VelocityUnit<?>> div(Velocity<?> divisor) {
        return (Per<VoltsPerAngularAccelerationUnit, VelocityUnit<?>>) Measure.super.div(divisor);
    }


    @Override
    default Per<VoltsPerAngularAccelerationUnit, VelocityUnit<?>> per(VelocityUnit<?> divisorUnit) {
        return div(divisorUnit.one());
    }


    @Override
    default Mult<VoltsPerAngularAccelerationUnit, VoltageUnit> times(Voltage multiplier) {
        return (Mult<VoltsPerAngularAccelerationUnit, VoltageUnit>) Measure.super.times(multiplier);
    }

    @Override
    default Per<VoltsPerAngularAccelerationUnit, VoltageUnit> div(Voltage divisor) {
        return (Per<VoltsPerAngularAccelerationUnit, VoltageUnit>) Measure.super.div(divisor);
    }

    @Override
    default Per<VoltsPerAngularAccelerationUnit, VoltageUnit> per(VoltageUnit divisorUnit) {
        return div(divisorUnit.one());
    }

}