// Copyright (c) FIRST and other WPILib contributors.
// Open Source Software; you can modify and/or share it under the terms of
// the WPILib BSD license file in the root directory of this project.

// THIS FILE WAS AUTO-GENERATED BY ./wpiunits/generate_units.py. DO NOT MODIFY

package digilib.units.currentperangacc;

import edu.wpi.first.units.*;
import edu.wpi.first.units.measure.*;

import static digilib.units.currentperangacc.CurrentPerAngularAccelerationUnit.AmpsPerRadiansPerSecondPerSecond;

@SuppressWarnings({"unchecked", "cast", "checkstyle", "PMD"})
public interface CurrentPerAngularAcceleration extends Measure<CurrentPerAngularAccelerationUnit> {
    static CurrentPerAngularAcceleration ofRelativeUnits(double magnitude, CurrentPerAngularAccelerationUnit unit) {
        return new ImmutableCurrentPerAngularAcceleration(magnitude, unit.toBaseUnits(magnitude), unit);
    }

    static CurrentPerAngularAcceleration ofBaseUnits(double baseUnitMagnitude, CurrentPerAngularAccelerationUnit unit) {
        return new ImmutableCurrentPerAngularAcceleration(unit.fromBaseUnits(baseUnitMagnitude), baseUnitMagnitude, unit);
    }

    @Override
    CurrentPerAngularAcceleration copy();

    @Override
    default MutCurrentPerAngularAcceleration mutableCopy() {
        return new MutCurrentPerAngularAcceleration(magnitude(), baseUnitMagnitude(), unit());
    }

    @Override
    CurrentPerAngularAccelerationUnit unit();

    @Override
    default CurrentPerAngularAccelerationUnit baseUnit() { return unit().getBaseUnit(); }

    @Override
    default double in(CurrentPerAngularAccelerationUnit unit) {
        return unit.fromBaseUnits(baseUnitMagnitude());
    }

    @Override
    default CurrentPerAngularAcceleration unaryMinus() {
        return unit().ofBaseUnits(0 - baseUnitMagnitude());
    }

    @Override
    default CurrentPerAngularAcceleration plus(Measure<? extends CurrentPerAngularAccelerationUnit> other) {
        return unit().ofBaseUnits(baseUnitMagnitude() + other.baseUnitMagnitude());
    }

    @Override
    default CurrentPerAngularAcceleration minus(Measure<? extends CurrentPerAngularAccelerationUnit> other) {
        return unit().ofBaseUnits(baseUnitMagnitude() - other.baseUnitMagnitude());
    }

    @Override
    default CurrentPerAngularAcceleration times(double multiplier) {
        return unit().ofBaseUnits(baseUnitMagnitude() * multiplier);
    }

    @Override
    default CurrentPerAngularAcceleration div(double divisor) {
        return unit().ofBaseUnits(baseUnitMagnitude() / divisor);
    }

    @Override
    default Mult<CurrentPerAngularAccelerationUnit, AccelerationUnit<?>> times(Acceleration<?> multiplier) {
        return (Mult<CurrentPerAngularAccelerationUnit, AccelerationUnit<?>>) Measure.super.times(multiplier);
    }

    @Override
    default Per<CurrentPerAngularAccelerationUnit, AccelerationUnit<?>> div(Acceleration<?> divisor) {
        return (Per<CurrentPerAngularAccelerationUnit, AccelerationUnit<?>>) Measure.super.div(divisor);
    }

    @Override
    default Per<CurrentPerAngularAccelerationUnit, AccelerationUnit<?>> per(AccelerationUnit<?> divisorUnit) {
        return div(divisorUnit.one());
    }

    @Override
    default Mult<CurrentPerAngularAccelerationUnit, AngleUnit> times(Angle multiplier) {
        return (Mult<CurrentPerAngularAccelerationUnit, AngleUnit>) Measure.super.times(multiplier);
    }

    @Override
    default Per<CurrentPerAngularAccelerationUnit, AngleUnit> div(Angle divisor) {
        return (Per<CurrentPerAngularAccelerationUnit, AngleUnit>) Measure.super.div(divisor);
    }

    @Override
    default Per<CurrentPerAngularAccelerationUnit, AngleUnit> per(AngleUnit divisorUnit) {
        return div(divisorUnit.one());
    }


    @Override
    default Current times(AngularAcceleration multiplier) {
        return (Current) Measure.super.times(multiplier);
    }

    @Override
    default Per<CurrentPerAngularAccelerationUnit, AngularAccelerationUnit> div(AngularAcceleration divisor) {
        return (Per<CurrentPerAngularAccelerationUnit, AngularAccelerationUnit>) Measure.super.div(divisor);
    }

    @Override
    default Per<CurrentPerAngularAccelerationUnit, AngularAccelerationUnit> per(AngularAccelerationUnit divisorUnit) {
        return div(divisorUnit.one());
    }


    @Override
    default Mult<CurrentPerAngularAccelerationUnit, AngularMomentumUnit> times(AngularMomentum multiplier) {
        return (Mult<CurrentPerAngularAccelerationUnit, AngularMomentumUnit>) Measure.super.times(multiplier);
    }

    @Override
    default Per<CurrentPerAngularAccelerationUnit, AngularMomentumUnit> div(AngularMomentum divisor) {
        return (Per<CurrentPerAngularAccelerationUnit, AngularMomentumUnit>) Measure.super.div(divisor);
    }

    @Override
    default Per<CurrentPerAngularAccelerationUnit, AngularMomentumUnit> per(AngularMomentumUnit divisorUnit) {
        return div(divisorUnit.one());
    }


    @Override
    default Mult<CurrentPerAngularAccelerationUnit, AngularVelocityUnit> times(AngularVelocity multiplier) {
        return (Mult<CurrentPerAngularAccelerationUnit, AngularVelocityUnit>) Measure.super.times(multiplier);
    }

    @Override
    default Per<CurrentPerAngularAccelerationUnit, AngularVelocityUnit> div(AngularVelocity divisor) {
        return (Per<CurrentPerAngularAccelerationUnit, AngularVelocityUnit>) Measure.super.div(divisor);
    }

    @Override
    default Per<CurrentPerAngularAccelerationUnit, AngularVelocityUnit> per(AngularVelocityUnit divisorUnit) {
        return div(divisorUnit.one());
    }


    @Override
    default Mult<CurrentPerAngularAccelerationUnit, CurrentUnit> times(Current multiplier) {
        return (Mult<CurrentPerAngularAccelerationUnit, CurrentUnit>) Measure.super.times(multiplier);
    }

    @Override
    default Per<CurrentPerAngularAccelerationUnit, CurrentUnit> div(Current divisor) {
        return (Per<CurrentPerAngularAccelerationUnit, CurrentUnit>) Measure.super.div(divisor);
    }

    @Override
    default Per<CurrentPerAngularAccelerationUnit, CurrentUnit> per(CurrentUnit divisorUnit) {
        return div(divisorUnit.one());
    }

    @Override
    default CurrentPerAngularAcceleration div(Dimensionless divisor) {
        return AmpsPerRadiansPerSecondPerSecond.of(baseUnitMagnitude() / divisor.baseUnitMagnitude());
    }

    @Override
    default CurrentPerAngularAcceleration times(Dimensionless multiplier) {
        return AmpsPerRadiansPerSecondPerSecond.of(baseUnitMagnitude() * multiplier.baseUnitMagnitude());
    }


    @Override
    default Mult<CurrentPerAngularAccelerationUnit, DistanceUnit> times(Distance multiplier) {
        return (Mult<CurrentPerAngularAccelerationUnit, DistanceUnit>) Measure.super.times(multiplier);
    }

    @Override
    default Per<CurrentPerAngularAccelerationUnit, DistanceUnit> div(Distance divisor) {
        return (Per<CurrentPerAngularAccelerationUnit, DistanceUnit>) Measure.super.div(divisor);
    }

    @Override
    default Per<CurrentPerAngularAccelerationUnit, DistanceUnit> per(DistanceUnit divisorUnit) {
        return div(divisorUnit.one());
    }


    @Override
    default Mult<CurrentPerAngularAccelerationUnit, EnergyUnit> times(Energy multiplier) {
        return (Mult<CurrentPerAngularAccelerationUnit, EnergyUnit>) Measure.super.times(multiplier);
    }

    @Override
    default Per<CurrentPerAngularAccelerationUnit, EnergyUnit> div(Energy divisor) {
        return (Per<CurrentPerAngularAccelerationUnit, EnergyUnit>) Measure.super.div(divisor);
    }

    @Override
    default Per<CurrentPerAngularAccelerationUnit, EnergyUnit> per(EnergyUnit divisorUnit) {
        return div(divisorUnit.one());
    }


    @Override
    default Mult<CurrentPerAngularAccelerationUnit, ForceUnit> times(Force multiplier) {
        return (Mult<CurrentPerAngularAccelerationUnit, ForceUnit>) Measure.super.times(multiplier);
    }

    @Override
    default Per<CurrentPerAngularAccelerationUnit, ForceUnit> div(Force divisor) {
        return (Per<CurrentPerAngularAccelerationUnit, ForceUnit>) Measure.super.div(divisor);
    }

    @Override
    default Per<CurrentPerAngularAccelerationUnit, ForceUnit> per(ForceUnit divisorUnit) {
        return div(divisorUnit.one());
    }


    @Override
    default Mult<CurrentPerAngularAccelerationUnit, FrequencyUnit> times(Frequency multiplier) {
        return (Mult<CurrentPerAngularAccelerationUnit, FrequencyUnit>) Measure.super.times(multiplier);
    }

    @Override
    default Per<CurrentPerAngularAccelerationUnit, FrequencyUnit> div(Frequency divisor) {
        return (Per<CurrentPerAngularAccelerationUnit, FrequencyUnit>) Measure.super.div(divisor);
    }

    @Override
    default Per<CurrentPerAngularAccelerationUnit, FrequencyUnit> per(FrequencyUnit divisorUnit) {
        return div(divisorUnit.one());
    }


    @Override
    default Mult<CurrentPerAngularAccelerationUnit, LinearAccelerationUnit> times(LinearAcceleration multiplier) {
        return (Mult<CurrentPerAngularAccelerationUnit, LinearAccelerationUnit>) Measure.super.times(multiplier);
    }

    @Override
    default Per<CurrentPerAngularAccelerationUnit, LinearAccelerationUnit> div(LinearAcceleration divisor) {
        return (Per<CurrentPerAngularAccelerationUnit, LinearAccelerationUnit>) Measure.super.div(divisor);
    }

    @Override
    default Per<CurrentPerAngularAccelerationUnit, LinearAccelerationUnit> per(LinearAccelerationUnit divisorUnit) {
        return div(divisorUnit.one());
    }


    @Override
    default Mult<CurrentPerAngularAccelerationUnit, LinearMomentumUnit> times(LinearMomentum multiplier) {
        return (Mult<CurrentPerAngularAccelerationUnit, LinearMomentumUnit>) Measure.super.times(multiplier);
    }

    @Override
    default Per<CurrentPerAngularAccelerationUnit, LinearMomentumUnit> div(LinearMomentum divisor) {
        return (Per<CurrentPerAngularAccelerationUnit, LinearMomentumUnit>) Measure.super.div(divisor);
    }

    @Override
    default Per<CurrentPerAngularAccelerationUnit, LinearMomentumUnit> per(LinearMomentumUnit divisorUnit) {
        return div(divisorUnit.one());
    }


    @Override
    default Mult<CurrentPerAngularAccelerationUnit, LinearVelocityUnit> times(LinearVelocity multiplier) {
        return (Mult<CurrentPerAngularAccelerationUnit, LinearVelocityUnit>) Measure.super.times(multiplier);
    }

    @Override
    default Per<CurrentPerAngularAccelerationUnit, LinearVelocityUnit> div(LinearVelocity divisor) {
        return (Per<CurrentPerAngularAccelerationUnit, LinearVelocityUnit>) Measure.super.div(divisor);
    }

    @Override
    default Per<CurrentPerAngularAccelerationUnit, LinearVelocityUnit> per(LinearVelocityUnit divisorUnit) {
        return div(divisorUnit.one());
    }


    @Override
    default Mult<CurrentPerAngularAccelerationUnit, MassUnit> times(Mass multiplier) {
        return (Mult<CurrentPerAngularAccelerationUnit, MassUnit>) Measure.super.times(multiplier);
    }

    @Override
    default Per<CurrentPerAngularAccelerationUnit, MassUnit> div(Mass divisor) {
        return (Per<CurrentPerAngularAccelerationUnit, MassUnit>) Measure.super.div(divisor);
    }

    @Override
    default Per<CurrentPerAngularAccelerationUnit, MassUnit> per(MassUnit divisorUnit) {
        return div(divisorUnit.one());
    }


    @Override
    default Mult<CurrentPerAngularAccelerationUnit, MomentOfInertiaUnit> times(MomentOfInertia multiplier) {
        return (Mult<CurrentPerAngularAccelerationUnit, MomentOfInertiaUnit>) Measure.super.times(multiplier);
    }

    @Override
    default Per<CurrentPerAngularAccelerationUnit, MomentOfInertiaUnit> div(MomentOfInertia divisor) {
        return (Per<CurrentPerAngularAccelerationUnit, MomentOfInertiaUnit>) Measure.super.div(divisor);
    }

    @Override
    default Per<CurrentPerAngularAccelerationUnit, MomentOfInertiaUnit> per(MomentOfInertiaUnit divisorUnit) {
        return div(divisorUnit.one());
    }


    @Override
    default Mult<CurrentPerAngularAccelerationUnit, MultUnit<?, ?>> times(Mult<?, ?> multiplier) {
        return (Mult<CurrentPerAngularAccelerationUnit, MultUnit<?, ?>>) Measure.super.times(multiplier);
    }

    @Override
    default Per<CurrentPerAngularAccelerationUnit, MultUnit<?, ?>> div(Mult<?, ?> divisor) {
        return (Per<CurrentPerAngularAccelerationUnit, MultUnit<?, ?>>) Measure.super.div(divisor);
    }

    @Override
    default Per<CurrentPerAngularAccelerationUnit, MultUnit<?, ?>> per(MultUnit<?, ?> divisorUnit) {
        return div(divisorUnit.ofNative(1));
    }


    @Override
    default Mult<CurrentPerAngularAccelerationUnit, PerUnit<?, ?>> times(Per<?, ?> multiplier) {
        return (Mult<CurrentPerAngularAccelerationUnit, PerUnit<?, ?>>) Measure.super.times(multiplier);
    }

    @Override
    default Per<CurrentPerAngularAccelerationUnit, PerUnit<?, ?>> div(Per<?, ?> divisor) {
        return (Per<CurrentPerAngularAccelerationUnit, PerUnit<?, ?>>) Measure.super.div(divisor);
    }

    @Override
    default Per<CurrentPerAngularAccelerationUnit, PerUnit<?, ?>> per(PerUnit<?, ?> divisorUnit) {
        return div(divisorUnit.ofNative(1));
    }


    @Override
    default Mult<CurrentPerAngularAccelerationUnit, PowerUnit> times(Power multiplier) {
        return (Mult<CurrentPerAngularAccelerationUnit, PowerUnit>) Measure.super.times(multiplier);
    }

    @Override
    default Per<CurrentPerAngularAccelerationUnit, PowerUnit> div(Power divisor) {
        return (Per<CurrentPerAngularAccelerationUnit, PowerUnit>) Measure.super.div(divisor);
    }

    @Override
    default Per<CurrentPerAngularAccelerationUnit, PowerUnit> per(PowerUnit divisorUnit) {
        return div(divisorUnit.one());
    }


    @Override
    default Mult<CurrentPerAngularAccelerationUnit, ResistanceUnit> times(Resistance multiplier) {
        return (Mult<CurrentPerAngularAccelerationUnit, ResistanceUnit>) Measure.super.times(multiplier);
    }

    @Override
    default Per<CurrentPerAngularAccelerationUnit, ResistanceUnit> div(Resistance divisor) {
        return (Per<CurrentPerAngularAccelerationUnit, ResistanceUnit>) Measure.super.div(divisor);
    }

    @Override
    default Per<CurrentPerAngularAccelerationUnit, ResistanceUnit> per(ResistanceUnit divisorUnit) {
        return div(divisorUnit.one());
    }


    @Override
    default Mult<CurrentPerAngularAccelerationUnit, TemperatureUnit> times(Temperature multiplier) {
        return (Mult<CurrentPerAngularAccelerationUnit, TemperatureUnit>) Measure.super.times(multiplier);
    }

    @Override
    default Per<CurrentPerAngularAccelerationUnit, TemperatureUnit> div(Temperature divisor) {
        return (Per<CurrentPerAngularAccelerationUnit, TemperatureUnit>) Measure.super.div(divisor);
    }

    @Override
    default Per<CurrentPerAngularAccelerationUnit, TemperatureUnit> per(TemperatureUnit divisorUnit) {
        return div(divisorUnit.one());
    }


    @Override
    default Mult<CurrentPerAngularAccelerationUnit, TimeUnit> times(Time multiplier) {
        return (Mult<CurrentPerAngularAccelerationUnit, TimeUnit>) Measure.super.times(multiplier);
    }

    @Override
    default Velocity<CurrentPerAngularAccelerationUnit> div(Time divisor) {
        return VelocityUnit.combine(unit(), divisor.unit()).ofBaseUnits(baseUnitMagnitude() / divisor.baseUnitMagnitude());
    }

    @Override
    default Velocity<CurrentPerAngularAccelerationUnit> per(TimeUnit divisorUnit) {
        return div(divisorUnit.one());
    }


    @Override
    default Mult<CurrentPerAngularAccelerationUnit, TorqueUnit> times(Torque multiplier) {
        return (Mult<CurrentPerAngularAccelerationUnit, TorqueUnit>) Measure.super.times(multiplier);
    }

    @Override
    default Per<CurrentPerAngularAccelerationUnit, TorqueUnit> div(Torque divisor) {
        return (Per<CurrentPerAngularAccelerationUnit, TorqueUnit>) Measure.super.div(divisor);
    }

    @Override
    default Per<CurrentPerAngularAccelerationUnit, TorqueUnit> per(TorqueUnit divisorUnit) {
        return div(divisorUnit.one());
    }


    @Override
    default Mult<CurrentPerAngularAccelerationUnit, VelocityUnit<?>> times(Velocity<?> multiplier) {
        return (Mult<CurrentPerAngularAccelerationUnit, VelocityUnit<?>>) Measure.super.times(multiplier);
    }

    @Override
    default Per<CurrentPerAngularAccelerationUnit, VelocityUnit<?>> div(Velocity<?> divisor) {
        return (Per<CurrentPerAngularAccelerationUnit, VelocityUnit<?>>) Measure.super.div(divisor);
    }


    @Override
    default Per<CurrentPerAngularAccelerationUnit, VelocityUnit<?>> per(VelocityUnit<?> divisorUnit) {
        return div(divisorUnit.one());
    }


    @Override
    default Mult<CurrentPerAngularAccelerationUnit, VoltageUnit> times(Voltage multiplier) {
        return (Mult<CurrentPerAngularAccelerationUnit, VoltageUnit>) Measure.super.times(multiplier);
    }

    @Override
    default Per<CurrentPerAngularAccelerationUnit, VoltageUnit> div(Voltage divisor) {
        return (Per<CurrentPerAngularAccelerationUnit, VoltageUnit>) Measure.super.div(divisor);
    }

    @Override
    default Per<CurrentPerAngularAccelerationUnit, VoltageUnit> per(VoltageUnit divisorUnit) {
        return div(divisorUnit.one());
    }

}