// Copyright (c) FIRST and other WPILib contributors.
// Open Source Software; you can modify and/or share it under the terms of
// the WPILib BSD license file in the root directory of this project.

// THIS FILE WAS AUTO-GENERATED BY ./wpiunits/generate_units.py. DO NOT MODIFY

package digilib.units.currentperangvel;

import edu.wpi.first.units.*;
import edu.wpi.first.units.measure.*;

import static digilib.units.currentperangvel.CurrentPerAngularVelocityUnit.AmpsPerRadiansPerSecond;

@SuppressWarnings({"unchecked", "cast", "checkstyle", "PMD"})
public interface CurrentPerAngularVelocity extends Measure<CurrentPerAngularVelocityUnit> {
    static CurrentPerAngularVelocity ofRelativeUnits(double magnitude, CurrentPerAngularVelocityUnit unit) {
        return new ImmutableCurrentPerAngularVelocity(magnitude, unit.toBaseUnits(magnitude), unit);
    }

    static CurrentPerAngularVelocity ofBaseUnits(double baseUnitMagnitude, CurrentPerAngularVelocityUnit unit) {
        return new ImmutableCurrentPerAngularVelocity(unit.fromBaseUnits(baseUnitMagnitude), baseUnitMagnitude, unit);
    }

    @Override
    CurrentPerAngularVelocity copy();

    @Override
    default MutCurrentPerAngularVelocity mutableCopy() {
        return new MutCurrentPerAngularVelocity(magnitude(), baseUnitMagnitude(), unit());
    }

    @Override
    CurrentPerAngularVelocityUnit unit();

    @Override
    default CurrentPerAngularVelocityUnit baseUnit() { return unit().getBaseUnit(); }

    @Override
    default double in(CurrentPerAngularVelocityUnit unit) {
        return unit.fromBaseUnits(baseUnitMagnitude());
    }

    @Override
    default CurrentPerAngularVelocity unaryMinus() {
        return unit().ofBaseUnits(0 - baseUnitMagnitude());
    }

    @Override
    default CurrentPerAngularVelocity plus(Measure<? extends CurrentPerAngularVelocityUnit> other) {
        return unit().ofBaseUnits(baseUnitMagnitude() + other.baseUnitMagnitude());
    }

    @Override
    default CurrentPerAngularVelocity minus(Measure<? extends CurrentPerAngularVelocityUnit> other) {
        return unit().ofBaseUnits(baseUnitMagnitude() - other.baseUnitMagnitude());
    }

    @Override
    default CurrentPerAngularVelocity times(double multiplier) {
        return unit().ofBaseUnits(baseUnitMagnitude() * multiplier);
    }

    @Override
    default CurrentPerAngularVelocity div(double divisor) {
        return unit().ofBaseUnits(baseUnitMagnitude() / divisor);
    }


    @Override
    default Mult<CurrentPerAngularVelocityUnit, AccelerationUnit<?>> times(Acceleration<?> multiplier) {
        return (Mult<CurrentPerAngularVelocityUnit, AccelerationUnit<?>>) Measure.super.times(multiplier);
    }

    @Override
    default Per<CurrentPerAngularVelocityUnit, AccelerationUnit<?>> div(Acceleration<?> divisor) {
        return (Per<CurrentPerAngularVelocityUnit, AccelerationUnit<?>>) Measure.super.div(divisor);
    }

    @Override
    default Per<CurrentPerAngularVelocityUnit, AccelerationUnit<?>> per(AccelerationUnit<?> divisorUnit) {
        return div(divisorUnit.one());
    }


    @Override
    default Mult<CurrentPerAngularVelocityUnit, AngleUnit> times(Angle multiplier) {
        return (Mult<CurrentPerAngularVelocityUnit, AngleUnit>) Measure.super.times(multiplier);
    }

    @Override
    default Per<CurrentPerAngularVelocityUnit, AngleUnit> div(Angle divisor) {
        return (Per<CurrentPerAngularVelocityUnit, AngleUnit>) Measure.super.div(divisor);
    }

    @Override
    default Per<CurrentPerAngularVelocityUnit, AngleUnit> per(AngleUnit divisorUnit) {
        return div(divisorUnit.one());
    }


    @Override
    default Mult<CurrentPerAngularVelocityUnit, AngularAccelerationUnit> times(AngularAcceleration multiplier) {
        return (Mult<CurrentPerAngularVelocityUnit, AngularAccelerationUnit>) Measure.super.times(multiplier);
    }

    @Override
    default Per<CurrentPerAngularVelocityUnit, AngularAccelerationUnit> div(AngularAcceleration divisor) {
        return (Per<CurrentPerAngularVelocityUnit, AngularAccelerationUnit>) Measure.super.div(divisor);
    }

    @Override
    default Per<CurrentPerAngularVelocityUnit, AngularAccelerationUnit> per(AngularAccelerationUnit divisorUnit) {
        return div(divisorUnit.one());
    }


    @Override
    default Mult<CurrentPerAngularVelocityUnit, AngularMomentumUnit> times(AngularMomentum multiplier) {
        return (Mult<CurrentPerAngularVelocityUnit, AngularMomentumUnit>) Measure.super.times(multiplier);
    }

    @Override
    default Per<CurrentPerAngularVelocityUnit, AngularMomentumUnit> div(AngularMomentum divisor) {
        return (Per<CurrentPerAngularVelocityUnit, AngularMomentumUnit>) Measure.super.div(divisor);
    }

    @Override
    default Per<CurrentPerAngularVelocityUnit, AngularMomentumUnit> per(AngularMomentumUnit divisorUnit) {
        return div(divisorUnit.one());
    }


    @Override
    default Current times(AngularVelocity multiplier) {
        return (Current) Measure.super.times(multiplier);
    }

    @Override
    default Per<CurrentPerAngularVelocityUnit, AngularVelocityUnit> div(AngularVelocity divisor) {
        return (Per<CurrentPerAngularVelocityUnit, AngularVelocityUnit>) Measure.super.div(divisor);
    }

    @Override
    default Per<CurrentPerAngularVelocityUnit, AngularVelocityUnit> per(AngularVelocityUnit divisorUnit) {
        return div(divisorUnit.one());
    }


    @Override
    default Mult<CurrentPerAngularVelocityUnit, CurrentUnit> times(Current multiplier) {
        return (Mult<CurrentPerAngularVelocityUnit, CurrentUnit>) Measure.super.times(multiplier);
    }

    @Override
    default Per<CurrentPerAngularVelocityUnit, CurrentUnit> div(Current divisor) {
        return (Per<CurrentPerAngularVelocityUnit, CurrentUnit>) Measure.super.div(divisor);
    }

    @Override
    default Per<CurrentPerAngularVelocityUnit, CurrentUnit> per(CurrentUnit divisorUnit) {
        return div(divisorUnit.one());
    }

    @Override
    default CurrentPerAngularVelocity div(Dimensionless divisor) {
        return AmpsPerRadiansPerSecond.of(baseUnitMagnitude() / divisor.baseUnitMagnitude());
    }

    @Override
    default CurrentPerAngularVelocity times(Dimensionless multiplier) {
        return AmpsPerRadiansPerSecond.of(baseUnitMagnitude() * multiplier.baseUnitMagnitude());
    }


    @Override
    default Mult<CurrentPerAngularVelocityUnit, DistanceUnit> times(Distance multiplier) {
        return (Mult<CurrentPerAngularVelocityUnit, DistanceUnit>) Measure.super.times(multiplier);
    }

    @Override
    default Per<CurrentPerAngularVelocityUnit, DistanceUnit> div(Distance divisor) {
        return (Per<CurrentPerAngularVelocityUnit, DistanceUnit>) Measure.super.div(divisor);
    }

    @Override
    default Per<CurrentPerAngularVelocityUnit, DistanceUnit> per(DistanceUnit divisorUnit) {
        return div(divisorUnit.one());
    }


    @Override
    default Mult<CurrentPerAngularVelocityUnit, EnergyUnit> times(Energy multiplier) {
        return (Mult<CurrentPerAngularVelocityUnit, EnergyUnit>) Measure.super.times(multiplier);
    }

    @Override
    default Per<CurrentPerAngularVelocityUnit, EnergyUnit> div(Energy divisor) {
        return (Per<CurrentPerAngularVelocityUnit, EnergyUnit>) Measure.super.div(divisor);
    }

    @Override
    default Per<CurrentPerAngularVelocityUnit, EnergyUnit> per(EnergyUnit divisorUnit) {
        return div(divisorUnit.one());
    }


    @Override
    default Mult<CurrentPerAngularVelocityUnit, ForceUnit> times(Force multiplier) {
        return (Mult<CurrentPerAngularVelocityUnit, ForceUnit>) Measure.super.times(multiplier);
    }

    @Override
    default Per<CurrentPerAngularVelocityUnit, ForceUnit> div(Force divisor) {
        return (Per<CurrentPerAngularVelocityUnit, ForceUnit>) Measure.super.div(divisor);
    }

    @Override
    default Per<CurrentPerAngularVelocityUnit, ForceUnit> per(ForceUnit divisorUnit) {
        return div(divisorUnit.one());
    }


    @Override
    default Mult<CurrentPerAngularVelocityUnit, FrequencyUnit> times(Frequency multiplier) {
        return (Mult<CurrentPerAngularVelocityUnit, FrequencyUnit>) Measure.super.times(multiplier);
    }

    @Override
    default Per<CurrentPerAngularVelocityUnit, FrequencyUnit> div(Frequency divisor) {
        return (Per<CurrentPerAngularVelocityUnit, FrequencyUnit>) Measure.super.div(divisor);
    }

    @Override
    default Per<CurrentPerAngularVelocityUnit, FrequencyUnit> per(FrequencyUnit divisorUnit) {
        return div(divisorUnit.one());
    }


    @Override
    default Mult<CurrentPerAngularVelocityUnit, LinearAccelerationUnit> times(LinearAcceleration multiplier) {
        return (Mult<CurrentPerAngularVelocityUnit, LinearAccelerationUnit>) Measure.super.times(multiplier);
    }

    @Override
    default Per<CurrentPerAngularVelocityUnit, LinearAccelerationUnit> div(LinearAcceleration divisor) {
        return (Per<CurrentPerAngularVelocityUnit, LinearAccelerationUnit>) Measure.super.div(divisor);
    }

    @Override
    default Per<CurrentPerAngularVelocityUnit, LinearAccelerationUnit> per(LinearAccelerationUnit divisorUnit) {
        return div(divisorUnit.one());
    }


    @Override
    default Mult<CurrentPerAngularVelocityUnit, LinearMomentumUnit> times(LinearMomentum multiplier) {
        return (Mult<CurrentPerAngularVelocityUnit, LinearMomentumUnit>) Measure.super.times(multiplier);
    }

    @Override
    default Per<CurrentPerAngularVelocityUnit, LinearMomentumUnit> div(LinearMomentum divisor) {
        return (Per<CurrentPerAngularVelocityUnit, LinearMomentumUnit>) Measure.super.div(divisor);
    }

    @Override
    default Per<CurrentPerAngularVelocityUnit, LinearMomentumUnit> per(LinearMomentumUnit divisorUnit) {
        return div(divisorUnit.one());
    }


    @Override
    default Mult<CurrentPerAngularVelocityUnit, LinearVelocityUnit> times(LinearVelocity multiplier) {
        return (Mult<CurrentPerAngularVelocityUnit, LinearVelocityUnit>) Measure.super.times(multiplier);
    }

    @Override
    default Per<CurrentPerAngularVelocityUnit, LinearVelocityUnit> div(LinearVelocity divisor) {
        return (Per<CurrentPerAngularVelocityUnit, LinearVelocityUnit>) Measure.super.div(divisor);
    }

    @Override
    default Per<CurrentPerAngularVelocityUnit, LinearVelocityUnit> per(LinearVelocityUnit divisorUnit) {
        return div(divisorUnit.one());
    }


    @Override
    default Mult<CurrentPerAngularVelocityUnit, MassUnit> times(Mass multiplier) {
        return (Mult<CurrentPerAngularVelocityUnit, MassUnit>) Measure.super.times(multiplier);
    }

    @Override
    default Per<CurrentPerAngularVelocityUnit, MassUnit> div(Mass divisor) {
        return (Per<CurrentPerAngularVelocityUnit, MassUnit>) Measure.super.div(divisor);
    }

    @Override
    default Per<CurrentPerAngularVelocityUnit, MassUnit> per(MassUnit divisorUnit) {
        return div(divisorUnit.one());
    }


    @Override
    default Mult<CurrentPerAngularVelocityUnit, MomentOfInertiaUnit> times(MomentOfInertia multiplier) {
        return (Mult<CurrentPerAngularVelocityUnit, MomentOfInertiaUnit>) Measure.super.times(multiplier);
    }

    @Override
    default Per<CurrentPerAngularVelocityUnit, MomentOfInertiaUnit> div(MomentOfInertia divisor) {
        return (Per<CurrentPerAngularVelocityUnit, MomentOfInertiaUnit>) Measure.super.div(divisor);
    }

    @Override
    default Per<CurrentPerAngularVelocityUnit, MomentOfInertiaUnit> per(MomentOfInertiaUnit divisorUnit) {
        return div(divisorUnit.one());
    }


    @Override
    default Mult<CurrentPerAngularVelocityUnit, MultUnit<?, ?>> times(Mult<?, ?> multiplier) {
        return (Mult<CurrentPerAngularVelocityUnit, MultUnit<?, ?>>) Measure.super.times(multiplier);
    }

    @Override
    default Per<CurrentPerAngularVelocityUnit, MultUnit<?, ?>> div(Mult<?, ?> divisor) {
        return (Per<CurrentPerAngularVelocityUnit, MultUnit<?, ?>>) Measure.super.div(divisor);
    }

    @Override
    default Per<CurrentPerAngularVelocityUnit, MultUnit<?, ?>> per(MultUnit<?, ?> divisorUnit) {
        return div(divisorUnit.ofNative(1));
    }


    @Override
    default Mult<CurrentPerAngularVelocityUnit, PerUnit<?, ?>> times(Per<?, ?> multiplier) {
        return (Mult<CurrentPerAngularVelocityUnit, PerUnit<?, ?>>) Measure.super.times(multiplier);
    }

    @Override
    default Per<CurrentPerAngularVelocityUnit, PerUnit<?, ?>> div(Per<?, ?> divisor) {
        return (Per<CurrentPerAngularVelocityUnit, PerUnit<?, ?>>) Measure.super.div(divisor);
    }

    @Override
    default Per<CurrentPerAngularVelocityUnit, PerUnit<?, ?>> per(PerUnit<?, ?> divisorUnit) {
        return div(divisorUnit.ofNative(1));
    }


    @Override
    default Mult<CurrentPerAngularVelocityUnit, PowerUnit> times(Power multiplier) {
        return (Mult<CurrentPerAngularVelocityUnit, PowerUnit>) Measure.super.times(multiplier);
    }

    @Override
    default Per<CurrentPerAngularVelocityUnit, PowerUnit> div(Power divisor) {
        return (Per<CurrentPerAngularVelocityUnit, PowerUnit>) Measure.super.div(divisor);
    }

    @Override
    default Per<CurrentPerAngularVelocityUnit, PowerUnit> per(PowerUnit divisorUnit) {
        return div(divisorUnit.one());
    }


    @Override
    default Mult<CurrentPerAngularVelocityUnit, ResistanceUnit> times(Resistance multiplier) {
        return (Mult<CurrentPerAngularVelocityUnit, ResistanceUnit>) Measure.super.times(multiplier);
    }

    @Override
    default Per<CurrentPerAngularVelocityUnit, ResistanceUnit> div(Resistance divisor) {
        return (Per<CurrentPerAngularVelocityUnit, ResistanceUnit>) Measure.super.div(divisor);
    }

    @Override
    default Per<CurrentPerAngularVelocityUnit, ResistanceUnit> per(ResistanceUnit divisorUnit) {
        return div(divisorUnit.one());
    }


    @Override
    default Mult<CurrentPerAngularVelocityUnit, TemperatureUnit> times(Temperature multiplier) {
        return (Mult<CurrentPerAngularVelocityUnit, TemperatureUnit>) Measure.super.times(multiplier);
    }

    @Override
    default Per<CurrentPerAngularVelocityUnit, TemperatureUnit> div(Temperature divisor) {
        return (Per<CurrentPerAngularVelocityUnit, TemperatureUnit>) Measure.super.div(divisor);
    }

    @Override
    default Per<CurrentPerAngularVelocityUnit, TemperatureUnit> per(TemperatureUnit divisorUnit) {
        return div(divisorUnit.one());
    }


    @Override
    default Mult<CurrentPerAngularVelocityUnit, TimeUnit> times(Time multiplier) {
        return (Mult<CurrentPerAngularVelocityUnit, TimeUnit>) Measure.super.times(multiplier);
    }

    @Override
    default Velocity<CurrentPerAngularVelocityUnit> div(Time divisor) {
        return VelocityUnit.combine(unit(), divisor.unit()).ofBaseUnits(baseUnitMagnitude() / divisor.baseUnitMagnitude());
    }

    @Override
    default Velocity<CurrentPerAngularVelocityUnit> per(TimeUnit divisorUnit) {
        return div(divisorUnit.one());
    }


    @Override
    default Mult<CurrentPerAngularVelocityUnit, TorqueUnit> times(Torque multiplier) {
        return (Mult<CurrentPerAngularVelocityUnit, TorqueUnit>) Measure.super.times(multiplier);
    }

    @Override
    default Per<CurrentPerAngularVelocityUnit, TorqueUnit> div(Torque divisor) {
        return (Per<CurrentPerAngularVelocityUnit, TorqueUnit>) Measure.super.div(divisor);
    }

    @Override
    default Per<CurrentPerAngularVelocityUnit, TorqueUnit> per(TorqueUnit divisorUnit) {
        return div(divisorUnit.one());
    }


    @Override
    default Mult<CurrentPerAngularVelocityUnit, VelocityUnit<?>> times(Velocity<?> multiplier) {
        return (Mult<CurrentPerAngularVelocityUnit, VelocityUnit<?>>) Measure.super.times(multiplier);
    }

    @Override
    default Per<CurrentPerAngularVelocityUnit, VelocityUnit<?>> div(Velocity<?> divisor) {
        return (Per<CurrentPerAngularVelocityUnit, VelocityUnit<?>>) Measure.super.div(divisor);
    }

    @Override
    default Per<CurrentPerAngularVelocityUnit, VelocityUnit<?>> per(VelocityUnit<?> divisorUnit) {
        return div(divisorUnit.one());
    }


    @Override
    default Mult<CurrentPerAngularVelocityUnit, VoltageUnit> times(Voltage multiplier) {
        return (Mult<CurrentPerAngularVelocityUnit, VoltageUnit>) Measure.super.times(multiplier);
    }

    @Override
    default Per<CurrentPerAngularVelocityUnit, VoltageUnit> div(Voltage divisor) {
        return (Per<CurrentPerAngularVelocityUnit, VoltageUnit>) Measure.super.div(divisor);
    }

    @Override
    default Per<CurrentPerAngularVelocityUnit, VoltageUnit> per(VoltageUnit divisorUnit) {
        return div(divisorUnit.one());
    }

}