// Copyright (c) FIRST and other WPILib contributors.
// Open Source Software; you can modify and/or share it under the terms of
// the WPILib BSD license file in the root directory of this project.

// THIS FILE WAS AUTO-GENERATED BY ./wpiunits/generate_units.py. DO NOT MODIFY

package digilib.units.voltsperangvel;

import static digilib.units.voltsperangvel.VoltsPerAngularVelocityUnit.VoltsPerRadiansPerSecond;

import edu.wpi.first.units.*;
import edu.wpi.first.units.measure.*;

@SuppressWarnings({"unchecked", "cast", "checkstyle", "PMD"})
public interface VoltsPerAngularVelocity extends Measure<VoltsPerAngularVelocityUnit> {
    static  VoltsPerAngularVelocity ofRelativeUnits(double magnitude, VoltsPerAngularVelocityUnit unit) {
        return new ImmutableVoltsPerAngularVelocity(magnitude, unit.toBaseUnits(magnitude), unit);
    }

    static  VoltsPerAngularVelocity ofBaseUnits(double baseUnitMagnitude, VoltsPerAngularVelocityUnit unit) {
        return new ImmutableVoltsPerAngularVelocity(unit.fromBaseUnits(baseUnitMagnitude), baseUnitMagnitude, unit);
    }

    @Override
    VoltsPerAngularVelocity copy();

    @Override
    default MutVoltsPerAngularVelocity mutableCopy() {
        return new MutVoltsPerAngularVelocity(magnitude(), baseUnitMagnitude(), unit());
    }

    @Override
    VoltsPerAngularVelocityUnit unit();

    @Override
    default VoltsPerAngularVelocityUnit baseUnit() { return unit().getBaseUnit(); }

    @Override
    default double in(VoltsPerAngularVelocityUnit unit) {
        return unit.fromBaseUnits(baseUnitMagnitude());
    }

    @Override
    default VoltsPerAngularVelocity unaryMinus() {
        return unit().ofBaseUnits(0 - baseUnitMagnitude());
    }

    @Override
    default VoltsPerAngularVelocity plus(Measure<? extends VoltsPerAngularVelocityUnit> other) {
        return unit().ofBaseUnits(baseUnitMagnitude() + other.baseUnitMagnitude());
    }

    @Override
    default VoltsPerAngularVelocity minus(Measure<? extends VoltsPerAngularVelocityUnit> other) {
        return unit().ofBaseUnits(baseUnitMagnitude() - other.baseUnitMagnitude());
    }

    @Override
    default VoltsPerAngularVelocity times(double multiplier) {
        return unit().ofBaseUnits(baseUnitMagnitude() * multiplier);
    }

    @Override
    default VoltsPerAngularVelocity div(double divisor) {
        return unit().ofBaseUnits(baseUnitMagnitude() / divisor);
    }

    @Override
    default Mult<VoltsPerAngularVelocityUnit, AccelerationUnit<?>> times(Acceleration<?> multiplier) {
        return (Mult<VoltsPerAngularVelocityUnit, AccelerationUnit<?>>) Measure.super.times(multiplier);
    }

    @Override
    default Per<VoltsPerAngularVelocityUnit, AccelerationUnit<?>> div(Acceleration<?> divisor) {
        return (Per<VoltsPerAngularVelocityUnit, AccelerationUnit<?>>) Measure.super.div(divisor);
    }

    @Override
    default Per<VoltsPerAngularVelocityUnit, AccelerationUnit<?>> per(AccelerationUnit<?> divisorUnit) {
        return div(divisorUnit.one());
    }

    @Override
    default Mult<VoltsPerAngularVelocityUnit, AngleUnit> times(Angle multiplier) {
        return (Mult<VoltsPerAngularVelocityUnit, AngleUnit>) Measure.super.times(multiplier);
    }

    @Override
    default Per<VoltsPerAngularVelocityUnit, AngleUnit> div(Angle divisor) {
        return (Per<VoltsPerAngularVelocityUnit, AngleUnit>) Measure.super.div(divisor);
    }

    @Override
    default Per<VoltsPerAngularVelocityUnit, AngleUnit> per(AngleUnit divisorUnit) {
        return div(divisorUnit.one());
    }


    @Override
    default Mult<VoltsPerAngularVelocityUnit, AngularAccelerationUnit> times(AngularAcceleration multiplier) {
        return (Mult<VoltsPerAngularVelocityUnit, AngularAccelerationUnit>) Measure.super.times(multiplier);
    }

    @Override
    default Per<VoltsPerAngularVelocityUnit, AngularAccelerationUnit> div(AngularAcceleration divisor) {
        return (Per<VoltsPerAngularVelocityUnit, AngularAccelerationUnit>) Measure.super.div(divisor);
    }

    @Override
    default Per<VoltsPerAngularVelocityUnit, AngularAccelerationUnit> per(AngularAccelerationUnit divisorUnit) {
        return div(divisorUnit.one());
    }


    @Override
    default Mult<VoltsPerAngularVelocityUnit, AngularMomentumUnit> times(AngularMomentum multiplier) {
        return (Mult<VoltsPerAngularVelocityUnit, AngularMomentumUnit>) Measure.super.times(multiplier);
    }

    @Override
    default Per<VoltsPerAngularVelocityUnit, AngularMomentumUnit> div(AngularMomentum divisor) {
        return (Per<VoltsPerAngularVelocityUnit, AngularMomentumUnit>) Measure.super.div(divisor);
    }

    @Override
    default Per<VoltsPerAngularVelocityUnit, AngularMomentumUnit> per(AngularMomentumUnit divisorUnit) {
        return div(divisorUnit.one());
    }


    @Override
    default Voltage times(AngularVelocity multiplier) {
        return (Voltage) Measure.super.times(multiplier);
    }

    @Override
    default Per<VoltsPerAngularVelocityUnit, AngularVelocityUnit> div(AngularVelocity divisor) {
        return (Per<VoltsPerAngularVelocityUnit, AngularVelocityUnit>) Measure.super.div(divisor);
    }

    @Override
    default Per<VoltsPerAngularVelocityUnit, AngularVelocityUnit> per(AngularVelocityUnit divisorUnit) {
        return div(divisorUnit.one());
    }


    @Override
    default Mult<VoltsPerAngularVelocityUnit, CurrentUnit> times(Current multiplier) {
        return (Mult<VoltsPerAngularVelocityUnit, CurrentUnit>) Measure.super.times(multiplier);
    }

    @Override
    default Per<VoltsPerAngularVelocityUnit, CurrentUnit> div(Current divisor) {
        return (Per<VoltsPerAngularVelocityUnit, CurrentUnit>) Measure.super.div(divisor);
    }

    @Override
    default Per<VoltsPerAngularVelocityUnit, CurrentUnit> per(CurrentUnit divisorUnit) {
        return div(divisorUnit.one());
    }

    @Override
    default VoltsPerAngularVelocity div(Dimensionless divisor) {
        return VoltsPerRadiansPerSecond.of(baseUnitMagnitude() / divisor.baseUnitMagnitude());
    }

    @Override
    default VoltsPerAngularVelocity times(Dimensionless multiplier) {
        return VoltsPerRadiansPerSecond.of(baseUnitMagnitude() * multiplier.baseUnitMagnitude());
    }


    @Override
    default Mult<VoltsPerAngularVelocityUnit, DistanceUnit> times(Distance multiplier) {
        return (Mult<VoltsPerAngularVelocityUnit, DistanceUnit>) Measure.super.times(multiplier);
    }

    @Override
    default Per<VoltsPerAngularVelocityUnit, DistanceUnit> div(Distance divisor) {
        return (Per<VoltsPerAngularVelocityUnit, DistanceUnit>) Measure.super.div(divisor);
    }

    @Override
    default Per<VoltsPerAngularVelocityUnit, DistanceUnit> per(DistanceUnit divisorUnit) {
        return div(divisorUnit.one());
    }


    @Override
    default Mult<VoltsPerAngularVelocityUnit, EnergyUnit> times(Energy multiplier) {
        return (Mult<VoltsPerAngularVelocityUnit, EnergyUnit>) Measure.super.times(multiplier);
    }

    @Override
    default Per<VoltsPerAngularVelocityUnit, EnergyUnit> div(Energy divisor) {
        return (Per<VoltsPerAngularVelocityUnit, EnergyUnit>) Measure.super.div(divisor);
    }

    @Override
    default Per<VoltsPerAngularVelocityUnit, EnergyUnit> per(EnergyUnit divisorUnit) {
        return div(divisorUnit.one());
    }


    @Override
    default Mult<VoltsPerAngularVelocityUnit, ForceUnit> times(Force multiplier) {
        return (Mult<VoltsPerAngularVelocityUnit, ForceUnit>) Measure.super.times(multiplier);
    }

    @Override
    default Per<VoltsPerAngularVelocityUnit, ForceUnit> div(Force divisor) {
        return (Per<VoltsPerAngularVelocityUnit, ForceUnit>) Measure.super.div(divisor);
    }

    @Override
    default Per<VoltsPerAngularVelocityUnit, ForceUnit> per(ForceUnit divisorUnit) {
        return div(divisorUnit.one());
    }


    @Override
    default Mult<VoltsPerAngularVelocityUnit, FrequencyUnit> times(Frequency multiplier) {
        return (Mult<VoltsPerAngularVelocityUnit, FrequencyUnit>) Measure.super.times(multiplier);
    }

    @Override
    default Per<VoltsPerAngularVelocityUnit, FrequencyUnit> div(Frequency divisor) {
        return (Per<VoltsPerAngularVelocityUnit, FrequencyUnit>) Measure.super.div(divisor);
    }

    @Override
    default Per<VoltsPerAngularVelocityUnit, FrequencyUnit> per(FrequencyUnit divisorUnit) {
        return div(divisorUnit.one());
    }


    @Override
    default Mult<VoltsPerAngularVelocityUnit, LinearAccelerationUnit> times(LinearAcceleration multiplier) {
        return (Mult<VoltsPerAngularVelocityUnit, LinearAccelerationUnit>) Measure.super.times(multiplier);
    }

    @Override
    default Per<VoltsPerAngularVelocityUnit, LinearAccelerationUnit> div(LinearAcceleration divisor) {
        return (Per<VoltsPerAngularVelocityUnit, LinearAccelerationUnit>) Measure.super.div(divisor);
    }

    @Override
    default Per<VoltsPerAngularVelocityUnit, LinearAccelerationUnit> per(LinearAccelerationUnit divisorUnit) {
        return div(divisorUnit.one());
    }


    @Override
    default Mult<VoltsPerAngularVelocityUnit, LinearMomentumUnit> times(LinearMomentum multiplier) {
        return (Mult<VoltsPerAngularVelocityUnit, LinearMomentumUnit>) Measure.super.times(multiplier);
    }

    @Override
    default Per<VoltsPerAngularVelocityUnit, LinearMomentumUnit> div(LinearMomentum divisor) {
        return (Per<VoltsPerAngularVelocityUnit, LinearMomentumUnit>) Measure.super.div(divisor);
    }

    @Override
    default Per<VoltsPerAngularVelocityUnit, LinearMomentumUnit> per(LinearMomentumUnit divisorUnit) {
        return div(divisorUnit.one());
    }


    @Override
    default Mult<VoltsPerAngularVelocityUnit, LinearVelocityUnit> times(LinearVelocity multiplier) {
        return (Mult<VoltsPerAngularVelocityUnit, LinearVelocityUnit>) Measure.super.times(multiplier);
    }

    @Override
    default Per<VoltsPerAngularVelocityUnit, LinearVelocityUnit> div(LinearVelocity divisor) {
        return (Per<VoltsPerAngularVelocityUnit, LinearVelocityUnit>) Measure.super.div(divisor);
    }

    @Override
    default Per<VoltsPerAngularVelocityUnit, LinearVelocityUnit> per(LinearVelocityUnit divisorUnit) {
        return div(divisorUnit.one());
    }


    @Override
    default Mult<VoltsPerAngularVelocityUnit, MassUnit> times(Mass multiplier) {
        return (Mult<VoltsPerAngularVelocityUnit, MassUnit>) Measure.super.times(multiplier);
    }

    @Override
    default Per<VoltsPerAngularVelocityUnit, MassUnit> div(Mass divisor) {
        return (Per<VoltsPerAngularVelocityUnit, MassUnit>) Measure.super.div(divisor);
    }

    @Override
    default Per<VoltsPerAngularVelocityUnit, MassUnit> per(MassUnit divisorUnit) {
        return div(divisorUnit.one());
    }


    @Override
    default Mult<VoltsPerAngularVelocityUnit, MomentOfInertiaUnit> times(MomentOfInertia multiplier) {
        return (Mult<VoltsPerAngularVelocityUnit, MomentOfInertiaUnit>) Measure.super.times(multiplier);
    }

    @Override
    default Per<VoltsPerAngularVelocityUnit, MomentOfInertiaUnit> div(MomentOfInertia divisor) {
        return (Per<VoltsPerAngularVelocityUnit, MomentOfInertiaUnit>) Measure.super.div(divisor);
    }

    @Override
    default Per<VoltsPerAngularVelocityUnit, MomentOfInertiaUnit> per(MomentOfInertiaUnit divisorUnit) {
        return div(divisorUnit.one());
    }


    @Override
    default Mult<VoltsPerAngularVelocityUnit, MultUnit<?, ?>> times(Mult<?, ?> multiplier) {
        return (Mult<VoltsPerAngularVelocityUnit, MultUnit<?, ?>>) Measure.super.times(multiplier);
    }

    @Override
    default Per<VoltsPerAngularVelocityUnit, MultUnit<?, ?>> div(Mult<?, ?> divisor) {
        return (Per<VoltsPerAngularVelocityUnit, MultUnit<?, ?>>) Measure.super.div(divisor);
    }

    @Override
    default Per<VoltsPerAngularVelocityUnit, MultUnit<?, ?>> per(MultUnit<?, ?> divisorUnit) {
        return div(divisorUnit.ofNative(1));
    }


    @Override
    default Mult<VoltsPerAngularVelocityUnit, PerUnit<?, ?>> times(Per<?, ?> multiplier) {
        return (Mult<VoltsPerAngularVelocityUnit, PerUnit<?, ?>>) Measure.super.times(multiplier);
    }

    @Override
    default Per<VoltsPerAngularVelocityUnit, PerUnit<?, ?>> div(Per<?, ?> divisor) {
        return (Per<VoltsPerAngularVelocityUnit, PerUnit<?, ?>>) Measure.super.div(divisor);
    }

    @Override
    default Per<VoltsPerAngularVelocityUnit, PerUnit<?, ?>> per(PerUnit<?, ?> divisorUnit) {
        return div(divisorUnit.ofNative(1));
    }


    @Override
    default Mult<VoltsPerAngularVelocityUnit, PowerUnit> times(Power multiplier) {
        return (Mult<VoltsPerAngularVelocityUnit, PowerUnit>) Measure.super.times(multiplier);
    }

    @Override
    default Per<VoltsPerAngularVelocityUnit, PowerUnit> div(Power divisor) {
        return (Per<VoltsPerAngularVelocityUnit, PowerUnit>) Measure.super.div(divisor);
    }

    @Override
    default Per<VoltsPerAngularVelocityUnit, PowerUnit> per(PowerUnit divisorUnit) {
        return div(divisorUnit.one());
    }


    @Override
    default Mult<VoltsPerAngularVelocityUnit, ResistanceUnit> times(Resistance multiplier) {
        return (Mult<VoltsPerAngularVelocityUnit, ResistanceUnit>) Measure.super.times(multiplier);
    }

    @Override
    default Per<VoltsPerAngularVelocityUnit, ResistanceUnit> div(Resistance divisor) {
        return (Per<VoltsPerAngularVelocityUnit, ResistanceUnit>) Measure.super.div(divisor);
    }

    @Override
    default Per<VoltsPerAngularVelocityUnit, ResistanceUnit> per(ResistanceUnit divisorUnit) {
        return div(divisorUnit.one());
    }


    @Override
    default Mult<VoltsPerAngularVelocityUnit, TemperatureUnit> times(Temperature multiplier) {
        return (Mult<VoltsPerAngularVelocityUnit, TemperatureUnit>) Measure.super.times(multiplier);
    }

    @Override
    default Per<VoltsPerAngularVelocityUnit, TemperatureUnit> div(Temperature divisor) {
        return (Per<VoltsPerAngularVelocityUnit, TemperatureUnit>) Measure.super.div(divisor);
    }

    @Override
    default Per<VoltsPerAngularVelocityUnit, TemperatureUnit> per(TemperatureUnit divisorUnit) {
        return div(divisorUnit.one());
    }


    @Override
    default Mult<VoltsPerAngularVelocityUnit, TimeUnit> times(Time multiplier) {
        return (Mult<VoltsPerAngularVelocityUnit, TimeUnit>) Measure.super.times(multiplier);
    }

    @Override
    default Velocity<VoltsPerAngularVelocityUnit> div(Time divisor) {
        return VelocityUnit.combine(unit(), divisor.unit()).ofBaseUnits(baseUnitMagnitude() / divisor.baseUnitMagnitude());
    }

    @Override
    default Velocity<VoltsPerAngularVelocityUnit> per(TimeUnit divisorUnit) {
        return div(divisorUnit.one());
    }


    @Override
    default Mult<VoltsPerAngularVelocityUnit, TorqueUnit> times(Torque multiplier) {
        return (Mult<VoltsPerAngularVelocityUnit, TorqueUnit>) Measure.super.times(multiplier);
    }

    @Override
    default Per<VoltsPerAngularVelocityUnit, TorqueUnit> div(Torque divisor) {
        return (Per<VoltsPerAngularVelocityUnit, TorqueUnit>) Measure.super.div(divisor);
    }

    @Override
    default Per<VoltsPerAngularVelocityUnit, TorqueUnit> per(TorqueUnit divisorUnit) {
        return div(divisorUnit.one());
    }


    @Override
    default Mult<VoltsPerAngularVelocityUnit, VelocityUnit<?>> times(Velocity<?> multiplier) {
        return (Mult<VoltsPerAngularVelocityUnit, VelocityUnit<?>>) Measure.super.times(multiplier);
    }

    @Override
    default Per<VoltsPerAngularVelocityUnit, VelocityUnit<?>> div(Velocity<?> divisor) {
        return (Per<VoltsPerAngularVelocityUnit, VelocityUnit<?>>) Measure.super.div(divisor);
    }


    @Override
    default Per<VoltsPerAngularVelocityUnit, VelocityUnit<?>> per(VelocityUnit<?> divisorUnit) {
        return div(divisorUnit.one());
    }


    @Override
    default Mult<VoltsPerAngularVelocityUnit, VoltageUnit> times(Voltage multiplier) {
        return (Mult<VoltsPerAngularVelocityUnit, VoltageUnit>) Measure.super.times(multiplier);
    }

    @Override
    default Per<VoltsPerAngularVelocityUnit, VoltageUnit> div(Voltage divisor) {
        return (Per<VoltsPerAngularVelocityUnit, VoltageUnit>) Measure.super.div(divisor);
    }

    @Override
    default Per<VoltsPerAngularVelocityUnit, VoltageUnit> per(VoltageUnit divisorUnit) {
        return div(divisorUnit.one());
    }

}